### ISSUE TITLE
Use the precompiled list of upcoming workshops

### ISSUE THREAD

**Issue by davidfarmer** [aimath/WebsiteRedesign#8]
In this redesign, you can assume that you have access to an HTML formatted
file of upcoming workshops.

You can download this one and use it for practice:

https://aimath.org/~farmer/tmp/upcoming

If you need two files: all upcoming, and open applications, just let me know.

Also let me know if you need a different format.

**Comment by dfinkle1** [comment]
added an include for the upcoming workshops in home.html
